[font]
# normal = "JetBrainsMono NFM SemiBold"
# bold = "JetBrainsMono NFM ExtraBold"
# size = 18

size = 20
[[font.normal]]
family = "JetBrainsMono NFM ExtraBold"

# [[font.bold]]
# family = "JetBrainsMono NFM"
# style = "ExtraBold"
